apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-trigger-rolebinding
  namespace: replay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-trigger-role
subjects:
- kind: ServiceAccount
  name: k8s-resource-sa
  namespace: replay

