apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: replay-trigger
spec:
  broker: default
  filter:
   attributes:
     type: com.video.replay.requested
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: replay-service
      namespace: replay

