apiVersion: v1
kind: ConfigMap
metadata:
  name: video-service-config
data:
  ingress_route_paths: |
    {
      "replay": "/replay",
    }
  event_templates: |
    {
      "replay": {"action": "replay", "data": "Sample data for replay"},
    }

